<?php
/**
 * Created by PhpStorm.
 * User: liam
 * Date: 24/02/19
 * Time: 18:17
 */

namespace LiamWiltshire\LaravelJitLoader\Tests;

use Illuminate\Database\Capsule\Manager;

class TestCase extends \PHPUnit\Framework\TestCase
{
    public $db;

    public $messages = [];

    public function setUp()
    {
        $this->configureDatabase();
        $this->migrateIdentitiesTable();
    }
    protected function configureDatabase()
    {
        $db = new Manager();
        $db->addConnection(array(
            'driver'    => 'sqlite',
            'database'  => ':memory:',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ));
        $db->bootEloquent();
        $db->setAsGlobal();

        $this->db = $db;
        $this->db->getConnection()->enableQueryLog();
    }

    public function migrateIdentitiesTable()
    {
        Manager::schema()->create('dummy_models', function ($table) {
            $table->increments('id');
            $table->integer('dummy_model_id');
            $table->timestamps();
        });

        $x = 100;
        while ($x > 0) {
            DummyModel::create(array('dummy_model_id' => $x));
            $x--;
        }

        Manager::schema()->create('trait_models', function ($table) {
            $table->increments('id');
            $table->integer('trait_model_id');
            $table->timestamps();
        });

        $x = 100;
        while ($x > 0) {
            TraitModel::create(array('trait_model_id' => $x));
            $x--;
        }

        Manager::schema()->create('traitless_models', function ($table) {
            $table->increments('id');
            $table->integer('traitless_model_id');
            $table->timestamps();
        });

        $x = 100;
        while ($x > 0) {
            TraitlessModel::create(array('traitless_model_id' => $x));
            $x--;
        }
    }

    public function __destruct()
    {
        if (!empty($this->messages)) {
            echo "Performance Data:\n";
            echo implode("\n", $this->messages);
            echo "\n";
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
